export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_CURRENT_TRACK_INFO = 'SET_CURRENT_TRACK_INFO'
export const SET_DURATION = 'SET_DURATION'

export const TOGGLE_LOADING_TRACK = 'TOGGLE_LOADING_TRACK'

export const UP_BY_ONE_SECOND = 'UP_BY_ONE_SECOND'

export const GET_ALL_SONGS = 'GET_ALL_SONGS'
export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_RECENT = 'GET_RECENT'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'

export const SET_ITEM = 'SET_ITEM'

export const FAVORITE_KEY = 'favorites'
export const RECENT_KEY = 'recent'
