export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_DURATION = 'SET_DURATION'

export const UP_BY_ONE_SECOND = 'UP_BY_ONE_SECOND'
